name: Deployment Branch on Comment

on:
  issue_comment:
    types: [ created ]

permissions:
  contents: read
  packages: write
  pull-requests: write

concurrency: branchdeploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: branchdeploy
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '!deploy'}}

    steps:
      - name: Create initial comment
        id: init_comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: "Working on the branchdeploy... "
      - name: Display all outputs as JSON
        run: |
          echo "${{ toJSON(github.event) }}"
      - name: fetch pullrequest
        id: pr
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ github.event.issue.pull_request.url }}
      - uses: actions/checkout@v5
        with:
          repository: ${{ fromJson(steps.pr.outputs.response).head.repo.clone_url }}
          ref: ${{ fromJson(steps.pr.outputs.response).head.ref }}
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
      - name: Update comment on success
        uses: peter-evans/create-or-update-comment@v4
        if: success()
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.init_comment.outputs.comment-id }}
          body: "Successfully deployed here:"
      - name: Update comment on error
        uses: peter-evans/create-or-update-comment@v4
        if: (!success())
        with:
          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ steps.init_comment.outputs.comment-id }}
          body: "Sorry, something went wrong :("
